/**
 * Common constants used across the application
 */

/**
 * Nacionalidades (Countries) - ISO 3166-1 alpha-2 codes
 * Common Latin American countries first, then alphabetically
 */
export const NACIONALIDADES = [
  // Common in Colombia (prioritized)
  { code: "CO", name: "Colombiana" },
  { code: "VE", name: "Venezolana" },
  { code: "EC", name: "Ecuatoriana" },
  { code: "PE", name: "Peruana" },
  { code: "BR", name: "Brasileña" },
  { code: "AR", name: "Argentina" },
  { code: "MX", name: "Mexicana" },
  { code: "US", name: "Estadounidense" },
  { code: "ES", name: "Española" },

  // Separator
  { code: "---", name: "───────────────", disabled: true },

  // All others alphabetically
  { code: "AF", name: "Afgana" },
  { code: "AL", name: "Albanesa" },
  { code: "DE", name: "Alemana" },
  { code: "AD", name: "Andorrana" },
  { code: "AO", name: "Angoleña" },
  { code: "AG", name: "Antiguana" },
  { code: "SA", name: "Árabe Saudita" },
  { code: "DZ", name: "Argelina" },
  { code: "AM", name: "Armenia" },
  { code: "AU", name: "Australiana" },
  { code: "AT", name: "Austriaca" },
  { code: "AZ", name: "Azerbaiyana" },
  { code: "BS", name: "Bahameña" },
  { code: "BD", name: "Bangladesí" },
  { code: "BB", name: "Barbadense" },
  { code: "BH", name: "Bareiní" },
  { code: "BE", name: "Belga" },
  { code: "BZ", name: "Beliceña" },
  { code: "BJ", name: "Beninesa" },
  { code: "BY", name: "Bielorrusa" },
  { code: "BO", name: "Boliviana" },
  { code: "BA", name: "Bosnia" },
  { code: "BW", name: "Botsuanesa" },
  { code: "BN", name: "Bruneana" },
  { code: "BG", name: "Búlgara" },
  { code: "BF", name: "Burkinesa" },
  { code: "BI", name: "Burundesa" },
  { code: "BT", name: "Butanesa" },
  { code: "CV", name: "Caboverdiana" },
  { code: "KH", name: "Camboyana" },
  { code: "CM", name: "Camerunesa" },
  { code: "CA", name: "Canadiense" },
  { code: "QA", name: "Catarí" },
  { code: "TD", name: "Chadiana" },
  { code: "CL", name: "Chilena" },
  { code: "CN", name: "China" },
  { code: "CY", name: "Chipriota" },
  { code: "VA", name: "Ciudad del Vaticano" },
  { code: "KM", name: "Comorense" },
  { code: "CG", name: "Congoleña" },
  { code: "CD", name: "Congoleña (RDC)" },
  { code: "KP", name: "Norcoreana" },
  { code: "KR", name: "Surcoreana" },
  { code: "CI", name: "Marfileña" },
  { code: "CR", name: "Costarricense" },
  { code: "HR", name: "Croata" },
  { code: "CU", name: "Cubana" },
  { code: "DK", name: "Danesa" },
  { code: "DM", name: "Dominiqués" },
  { code: "EG", name: "Egipcia" },
  { code: "SV", name: "Salvadoreña" },
  { code: "AE", name: "Emiratí" },
  { code: "ER", name: "Eritrea" },
  { code: "SK", name: "Eslovaca" },
  { code: "SI", name: "Eslovena" },
  { code: "EE", name: "Estonia" },
  { code: "ET", name: "Etíope" },
  { code: "PH", name: "Filipina" },
  { code: "FI", name: "Finlandesa" },
  { code: "FJ", name: "Fiyiana" },
  { code: "FR", name: "Francesa" },
  { code: "GA", name: "Gabonesa" },
  { code: "GM", name: "Gambiana" },
  { code: "GE", name: "Georgiana" },
  { code: "GH", name: "Ghanesa" },
  { code: "GD", name: "Granadina" },
  { code: "GR", name: "Griega" },
  { code: "GT", name: "Guatemalteca" },
  { code: "GN", name: "Guineana" },
  { code: "GQ", name: "Ecuatoguineana" },
  { code: "GW", name: "Guineana (Bissau)" },
  { code: "GY", name: "Guyanesa" },
  { code: "HT", name: "Haitiana" },
  { code: "HN", name: "Hondureña" },
  { code: "HU", name: "Húngara" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IQ", name: "Iraquí" },
  { code: "IR", name: "Iraní" },
  { code: "IE", name: "Irlandesa" },
  { code: "IS", name: "Islandesa" },
  { code: "IL", name: "Israelí" },
  { code: "IT", name: "Italiana" },
  { code: "JM", name: "Jamaiquina" },
  { code: "JP", name: "Japonesa" },
  { code: "JO", name: "Jordana" },
  { code: "KZ", name: "Kazaja" },
  { code: "KE", name: "Keniana" },
  { code: "KG", name: "Kirguisa" },
  { code: "KI", name: "Kiribatiana" },
  { code: "KW", name: "Kuwaití" },
  { code: "LA", name: "Laosiana" },
  { code: "LS", name: "Lesotense" },
  { code: "LV", name: "Letona" },
  { code: "LB", name: "Libanesa" },
  { code: "LR", name: "Liberiana" },
  { code: "LY", name: "Libia" },
  { code: "LI", name: "Liechtensteiniana" },
  { code: "LT", name: "Lituana" },
  { code: "LU", name: "Luxemburguesa" },
  { code: "MK", name: "Macedonia" },
  { code: "MG", name: "Malgache" },
  { code: "MY", name: "Malasia" },
  { code: "MW", name: "Malaui" },
  { code: "MV", name: "Maldiva" },
  { code: "ML", name: "Maliense" },
  { code: "MT", name: "Maltesa" },
  { code: "MA", name: "Marroquí" },
  { code: "MH", name: "Marshalesa" },
  { code: "MU", name: "Mauriciana" },
  { code: "MR", name: "Mauritana" },
  { code: "FM", name: "Micronesia" },
  { code: "MD", name: "Moldava" },
  { code: "MC", name: "Monegasca" },
  { code: "MN", name: "Mongola" },
  { code: "ME", name: "Montenegrina" },
  { code: "MZ", name: "Mozambiqueña" },
  { code: "MM", name: "Birmana" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauruana" },
  { code: "NP", name: "Nepalí" },
  { code: "NI", name: "Nicaragüense" },
  { code: "NE", name: "Nigerina" },
  { code: "NG", name: "Nigeriana" },
  { code: "NO", name: "Noruega" },
  { code: "NZ", name: "Neozelandesa" },
  { code: "OM", name: "Omaní" },
  { code: "NL", name: "Neerlandesa" },
  { code: "PK", name: "Pakistaní" },
  { code: "PW", name: "Palauana" },
  { code: "PS", name: "Palestina" },
  { code: "PA", name: "Panameña" },
  { code: "PG", name: "Papú" },
  { code: "PY", name: "Paraguaya" },
  { code: "PL", name: "Polaca" },
  { code: "PT", name: "Portuguesa" },
  { code: "GB", name: "Británica" },
  { code: "CF", name: "Centroafricana" },
  { code: "CZ", name: "Checa" },
  { code: "DO", name: "Dominicana" },
  { code: "RO", name: "Rumana" },
  { code: "RW", name: "Ruandesa" },
  { code: "RU", name: "Rusa" },
  { code: "WS", name: "Samoana" },
  { code: "KN", name: "Sancristobaleña" },
  { code: "SM", name: "Sanmarinense" },
  { code: "VC", name: "Sanvicentina" },
  { code: "SH", name: "Santalucense" },
  { code: "ST", name: "Santotomense" },
  { code: "SN", name: "Senegalesa" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychellense" },
  { code: "SL", name: "Sierraleonesa" },
  { code: "SG", name: "Singapurense" },
  { code: "SY", name: "Siria" },
  { code: "SO", name: "Somalí" },
  { code: "LK", name: "Cingalesa" },
  { code: "ZA", name: "Sudafricana" },
  { code: "SD", name: "Sudanesa" },
  { code: "SS", name: "Sursudanesa" },
  { code: "SE", name: "Sueca" },
  { code: "CH", name: "Suiza" },
  { code: "SR", name: "Surinamesa" },
  { code: "SZ", name: "Suazi" },
  { code: "TH", name: "Tailandesa" },
  { code: "TZ", name: "Tanzana" },
  { code: "TJ", name: "Tayika" },
  { code: "TL", name: "Timorense" },
  { code: "TG", name: "Togolesa" },
  { code: "TO", name: "Tongana" },
  { code: "TT", name: "Trinitense" },
  { code: "TN", name: "Tunecina" },
  { code: "TM", name: "Turcomana" },
  { code: "TR", name: "Turca" },
  { code: "TV", name: "Tuvaluana" },
  { code: "UA", name: "Ucraniana" },
  { code: "UG", name: "Ugandesa" },
  { code: "UY", name: "Uruguaya" },
  { code: "UZ", name: "Uzbeka" },
  { code: "VU", name: "Vanuatuense" },
  { code: "VN", name: "Vietnamita" },
  { code: "YE", name: "Yemení" },
  { code: "DJ", name: "Yibutiana" },
  { code: "ZM", name: "Zambiana" },
  { code: "ZW", name: "Zimbabuense" },
] as const

/**
 * EPS (Entidades Promotoras de Salud) Colombia
 * Top 5 most common first, then alphabetically
 */
export const EPS_OPTIONS = [
  // Top 5 más usadas (separadas)
  { value: "sura", label: "Sura" },
  { value: "sanitas", label: "Sanitas" },
  { value: "salud_total", label: "Salud Total" },
  { value: "nueva_eps", label: "Nueva EPS" },
  { value: "coosalud", label: "Coosalud EPS" },

  // Separator
  { value: "---", label: "───────────────", disabled: true },

  // Resto alfabéticamente
  { value: "aliansalud", label: "Aliansalud EPS" },
  { value: "anas_wayuu", label: "Anas Wayuu EPSI" },
  { value: "asmet_salud", label: "Asmet Salud" },
  { value: "asociacion_indigena_cauca", label: "Asociación Indígena del Cauca EPSI" },
  { value: "cajacopi_atlantico", label: "Cajacopi Atlántico" },
  { value: "capital_salud", label: "Capital Salud EPS-S" },
  { value: "capresoca", label: "Capresoca" },
  { value: "comfachoco", label: "Comfachocó" },
  { value: "comfaoriente", label: "Comfaoriente" },
  { value: "comfenalco_valle", label: "Comfenalco Valle" },
  { value: "compensar", label: "Compensar EPS" },
  { value: "dusakawi", label: "Dusakawi EPSI" },
  { value: "emssanar", label: "Emssanar" },
  { value: "epm", label: "EPM – Empresas Públicas de Medellín EPS" },
  { value: "eps_familiar", label: "EPS Familiar de Colombia" },
  { value: "famisanar", label: "Famisanar EPS" },
  { value: "fondo_pasivo_ferrocarriles", label: "Fondo de Pasivo Social de Ferrocarriles Nacionales de Colombia" },
  { value: "mallamas", label: "Mallamas EPSI" },
  { value: "mutual_ser", label: "Mutual Ser" },
  { value: "pijaos_salud", label: "Pijaos Salud EPSI" },
  { value: "salud_mia", label: "Salud Mía" },
  { value: "savia_salud", label: "Savia Salud EPS" },
  { value: "sos", label: "Servicio Occidental de Salud (SOS)" },
] as const
